### PR TITLE
Set Karen Puckett's status to 'InCommunity' in E2E tests

### PR DESCRIPTION
**Pull request by richpjames**
This was causing the E2E tests to fail

# Release checklist

As part of our continuous deployment strategy we must ensure that this work is
ready to be released at any point. Before merging to `main` we must first
confirm:

## Pre merge checklist

- [ ] Have all changes to any dependencies been deployed to both `preprod` and
    `production` in a backwards compatible way? (This includes our API,
    infrastructure, third-party integrations and any secrets or environment variables)
- [ ] Has a required data migration been included in this change or been done in
    advance?

## Post merge checklist

Once we've merged we now need to release this through to production before
considering it done.

[Find the build-and-deploy job in CircleCI](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-temporary-accommodation-ui)
and work through the following steps:

- [ ] Has the product manager asked to provide approval for this feature?
  - [ ] Has the product manager approved?
- [ ] Manually approve release to preprod
- [ ] Verify change released to preprod
- [ ] Manually approve release to prod
- [ ] Verify change released to production

Should a release fail at any step, you as the author should now lead the work to
fix it as soon as possible.

### CODE REVIEW

**Comment by pezholio** [comment]
I think we looked at this before - the problem with updating to `InCommunity` is a) it's not realistic, and b) it means they don't have an associated prison. I think there was some chat before about what to do, and I forget what the decision was. Lemme dig through Slack and confirm

**Comment by richpjames** [comment]
@pezholio Yep, this was mentioned [on the last PR when I tried to make this change](https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/489) maybe we could merge this whilst we wait for the chat to happen then we can revert it as it's a very minor change? 
As things stand I don't think the E2Es have passed this year and I'm worried that even if we fix this it might unearth other issues.

**Comment by pezholio** [comment]
Ah, good call, do they pass running locally? I thought not having a prison would mean the tests still failed?

**Comment by richpjames** [comment]
Good point, I haven't tried them locally. Will give it a go tomorrow

**Comment by pezholio** [comment]
`npm run test:e2e:ui` is your friend 👍

**Comment by richpjames** [comment]
I didn't realise it was that easy. 
As you suspected it doesn't pass as Karen doesn't have a Prison

**Pull request closed without merging**
